delim = "  "

[[bar]]
name = ""
command = "date"
args = ['+%a, %d %b %H:%M']
interval = 5
[[bar]]
name = ""
command = "./bars/battery.sh"
interval = 5
[[bar]]
name = ""
command = "./bars/volume.sh"
interval = 1
[[bar]]
name = "ï„œ "
command = "./bars/kb_layout.sh"
interval = 1
[[bar]]
name = ""
command = "./bars/darksky_weather.sh"
interval = 600
